// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjuurNUSzm-BV4IYIsyH_ToDkn7LvoVPU',
    appId: '1:171387529098:web:6a29692e2e32be7d548a73',
    messagingSenderId: '171387529098',
    projectId: 'restaurantfirebase-d8067',
    authDomain: 'restaurantfirebase-d8067.firebaseapp.com',
    storageBucket: 'restaurantfirebase-d8067.firebasestorage.app',
    measurementId: 'G-B2CH64J1XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATVKa-VqjNjbXVnC11G1wSF5QMROlLOt0',
    appId: '1:171387529098:android:5426052c8a3c41f8548a73',
    messagingSenderId: '171387529098',
    projectId: 'restaurantfirebase-d8067',
    storageBucket: 'restaurantfirebase-d8067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpQhF7brDaZKBsIpqe_FRwsXeSUeynGHY',
    appId: '1:171387529098:ios:da55ffc40133eed0548a73',
    messagingSenderId: '171387529098',
    projectId: 'restaurantfirebase-d8067',
    storageBucket: 'restaurantfirebase-d8067.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpQhF7brDaZKBsIpqe_FRwsXeSUeynGHY',
    appId: '1:171387529098:ios:da55ffc40133eed0548a73',
    messagingSenderId: '171387529098',
    projectId: 'restaurantfirebase-d8067',
    storageBucket: 'restaurantfirebase-d8067.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjuurNUSzm-BV4IYIsyH_ToDkn7LvoVPU',
    appId: '1:171387529098:web:3040ba2a82402291548a73',
    messagingSenderId: '171387529098',
    projectId: 'restaurantfirebase-d8067',
    authDomain: 'restaurantfirebase-d8067.firebaseapp.com',
    storageBucket: 'restaurantfirebase-d8067.firebasestorage.app',
    measurementId: 'G-WNVMY8C160',
  );
}
